### ISSUE TITLE
build fails on i686 (as, bad directive)

### ISSUE THREAD

**Issue by joriszwart** [neonics/qure#2]
I tried to build on i686, but it fails to assemble kernel.s:

```
$ make
WARNING: missing DOC/Abstraction.txt at util/doctools.pl line 158.
WARNING: missing DOC/Git.txt at util/doctools.pl line 158.
WARNING: missing DOC/IP.txt at util/doctools.pl line 158.
  M     bootloader 
  M     fonts 
  M     kernel 
  AS    kernel.o
kernel.s: Assembler messages:
kernel.s:20: Fatal error: bad .section directive: want a,w,x,M,S,G,T in string
```

For some reason it does not recognize the macro '.text16'.
## Additional info

```
$ uname -a
Linux libra 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:31:42 UTC 2014 i686 athlon i686 GNU/Linux
```

Ubuntu 14.04.1 LTS
Make: 3.81
AS: 2.24

**Comment by neonics** [comment]
Hi Joris,

Thanks for making an issue of this long-standing TODO: to get the kernel to build on Linux. :-)

It does recognize the ```.text16``` macro defined in kernel/macros.s containing ``` .section .text16, "rwx"```, but expects an ELF version of the .section directive, whereas the code uses PE/COFF (pei-i386) syntax. (See https://sourceware.org/binutils/docs-2.21/as/Section.html). 

Removing the ```r``` from  ```"rwx"``` fixes this error but more will follow, as ELF .section does not allow ```.section sectionname, subsection_number```.
I have not been able to find how to specify the object file format for AS; my guess is that if somehow AS is forced to write a pei-386 file, it will use recognize the PE/COFF syntax.
So much for binutils portability.

I'm in the process of transitioning to named subsections (i.e. ```.text$foo```) using a linker script, but it's not complete. And even then, the syntax may be different for both formats.

**Comment by neonics** [comment]
A small update:
It should now *build* on 64 bit ELF hosts, although the relocation information is lost, wreaking all kinds of havoc. Upon booting the generated iso you should see it hang in the bootloader saying the 'stabs' section would overwrite the BIOS. See issue #3.

It turns out that binutils has far more compatibility issues than I anticipated. I'll continue working on my own linker with both PE/COFF and ELF support.
